package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/spf13/cobra"
)

var observabilitySources = []string{"datadog.tf", "datadog-auth.tf", "datadog-hostname.tf", "datadog-radius.tf", "datadog-smallstep.tf", "datadog-usage.tf"}
var observabilityAddresses = []string{
	"datadog_dashboard_json.radius", "datadog_dashboard_json.smallstep",
	"datadog_logs_custom_pipeline.radius_owner", "datadog_logs_custom_pipeline.stepca",
	"datadog_monitor.radius_client_cert_expired", "datadog_monitor.radius_client_cert_expiring", "datadog_monitor.radius_down", "datadog_monitor.radius_no_accepts", "datadog_monitor.radius_server_cert_expiry",
	"datadog_monitor.stepca_cert_expiry", "datadog_monitor.stepca_decrypter", "datadog_monitor.stepca_health", "datadog_monitor.stepca_kms_errors", "datadog_monitor.stepca_no_issuance", "datadog_monitor.stepca_process", "datadog_monitor.stepca_rsa_health",
}

func observabilityCommand() *cobra.Command {
	var root, output string
	var check, dryRun bool
	command := &cobra.Command{Use: "observability", Short: "Generate the Datadog-only owner configuration and closed ownership handoff manifest", Args: cobra.NoArgs, SilenceUsage: true}
	command.AddCommand(observabilityPlanCommand())
	command.Flags().StringVar(&root, "root", "../..", "Authoritative repository source")
	command.Flags().StringVar(&output, "output", "", "Separate output directory; never the repository root")
	command.Flags().BoolVar(&check, "check", false, "Check generated bytes without writing")
	command.Flags().BoolVar(&dryRun, "dry-run", false, "Report output paths without writing")
	_ = command.MarkFlagRequired("output")
	command.RunE = func(cmd *cobra.Command, _ []string) error {
		input, err := filepath.Abs(root)
		if err != nil {
			return err
		}
		target, err := filepath.Abs(output)
		if err != nil {
			return err
		}
		if input == target {
			return errors.New("observability output must not be the source root")
		}
		files, err := observabilityFiles(input)
		if err != nil {
			return err
		}
		existing, err := filepath.Glob(filepath.Join(target, "*.tf"))
		if err != nil {
			return err
		}
		for _, path := range existing {
			if name := filepath.Base(path); name != "observability.tf" && name != "versions.tf" {
				return fmt.Errorf("unexpected Terraform owner file: %s", name)
			}
		}
		names := make([]string, 0, len(files))
		for name := range files {
			names = append(names, name)
		}
		sort.Strings(names)
		if !check && !dryRun {
			if err = os.MkdirAll(target, 0700); err != nil {
				return err
			}
		}
		for _, name := range names {
			path := filepath.Join(target, name)
			if check {
				actual, e := os.ReadFile(path)
				if e != nil || !bytes.Equal(actual, files[name]) {
					return fmt.Errorf("generated observability drift: %s", name)
				}
				continue
			}
			if dryRun {
				_, _ = fmt.Fprintln(cmd.OutOrStdout(), path)
				continue
			}
			if info, e := os.Lstat(path); e == nil && !info.Mode().IsRegular() {
				return fmt.Errorf("nonregular output refused: %s", name)
			}
			if err = os.WriteFile(path, files[name], 0600); err != nil {
				return err
			}
		}
		return nil
	}
	return command
}

// Copy only parsed authoritative monitoring blocks. No GCP/provider/backend,
// tfvars, state or credential files are read. Every external reference is closed.
func observabilityFiles(root string) (map[string][]byte, error) {
	var selected strings.Builder
	resources := map[string]bool{}
	locals := map[string]bool{}
	variables := map[string]bool{}
	substitutions := map[string]string{
		"google_project.this.project_id":                "var.project_id",
		"google_compute_instance.radius.name":           `"radius-primary"`,
		"google_compute_instance.radius_secondary.name": `"radius-secondary"`,
		"var.datadog_app_key":                           `"explicit-observability-owner"`,
	}
	for _, name := range observabilitySources {
		source, err := os.ReadFile(filepath.Join(root, name))
		if err != nil {
			return nil, err
		}
		file, diags := hclsyntax.ParseConfig(source, name, hcl.InitialPos)
		if diags.HasErrors() {
			return nil, diags
		}
		for _, block := range file.Body.(*hclsyntax.Body).Blocks {
			switch block.Type {
			case "provider":
				if len(block.Labels) != 1 || block.Labels[0] != "datadog" {
					return nil, errors.New("unexpected provider in monitoring source")
				}
				continue
			case "resource":
				address := strings.Join(block.Labels, ".")
				if !containsString(observabilityAddresses, address) || resources[address] || block.Body.Attributes["count"] == nil || block.Body.Attributes["for_each"] != nil {
					return nil, fmt.Errorf("unsupported monitoring owner %s", address)
				}
				resources[address] = true
			case "locals":
				for name := range block.Body.Attributes {
					if locals[name] {
						return nil, fmt.Errorf("duplicate local %s", name)
					}
					locals[name] = true
				}
			case "variable":
				if len(block.Labels) != 1 {
					return nil, errors.New("invalid monitoring variable")
				}
				variables[block.Labels[0]] = true
			default:
				return nil, fmt.Errorf("unsupported monitoring block %s", block.Type)
			}
			copied, err := rewriteObservabilityBlock(source, block, substitutions)
			if err != nil {
				return nil, err
			}
			selected.Write(copied)
			selected.WriteString("\n")
		}
	}
	for _, name := range observabilityAddresses {
		if !resources[name] {
			return nil, fmt.Errorf("missing authoritative owner %s", name)
		}
	}
	// Nonsecret query inputs are intentionally independent of compute variables.
	selected.WriteString(`
variable "project_id" { type = string }
variable "datadog_site" { type = string }
variable "datadog_monitor_notify" { type = string }
variable "enable_smallstep_ca" { type = bool }
variable "enable_acme_issuance_monitor" { type = bool }
variable "smallstep_ca_dns_name" { type = string }
variable "smallstep_acme_provisioner_name" { type = string }
variable "radius_vlan_policy" { type = object({ certificate_inventory = bool }) }
`)
	for _, name := range []string{"project_id", "datadog_site", "datadog_monitor_notify", "enable_smallstep_ca", "enable_acme_issuance_monitor", "smallstep_ca_dns_name", "smallstep_acme_provisioner_name", "radius_vlan_policy"} {
		if variables[name] {
			return nil, fmt.Errorf("duplicate owner variable %s", name)
		}
		variables[name] = true
	}
	config := []byte(selected.String())
	parsed, diags := hclsyntax.ParseConfig(config, "observability.tf", hcl.InitialPos)
	if diags.HasErrors() {
		return nil, diags
	}
	// Refuse unresolved references and filesystem/unknown function calls, including
	// ones inside nested resources. Loop-local and built-in count values are bounded.
	knownRoots := map[string]bool{"var": true, "local": true, "count": true, "string": true, "bool": true, "number": true}
	allowedCalls := map[string]bool{}
	for _, name := range []string{"set", "map", "object", "optional", "alltrue", "can", "ceil", "concat", "contains", "distinct", "element", "flatten", "floor", "join", "jsonencode", "keys", "length", "lookup", "max", "merge", "min", "regex", "replace", "slice", "sort", "sum", "toset", "trimspace", "try", "values"} {
		allowedCalls[name] = true
	}
	diagnostics := hclsyntax.VisitAll(parsed.Body.(*hclsyntax.Body), func(node hclsyntax.Node) hcl.Diagnostics {
		if call, ok := node.(*hclsyntax.FunctionCallExpr); ok && !allowedCalls[call.Name] {
			return hcl.Diagnostics{&hcl.Diagnostic{Severity: hcl.DiagError, Summary: "unsupported monitoring function " + call.Name}}
		}
		return nil
	})
	if diagnostics.HasErrors() {
		return nil, diagnostics
	}
	// Variables() preserves lexical scope inside for expressions; collecting
	// every nested traversal would incorrectly admit a loop name elsewhere.
	var checkBody func(*hclsyntax.Body) error
	checkBody = func(body *hclsyntax.Body) error {
		for _, attribute := range body.Attributes {
			for _, traversal := range attribute.Expr.Variables() {
				name := traversal.RootName()
				if !knownRoots[name] {
					return fmt.Errorf("unsupported monitoring reference %s", name)
				}
				if len(traversal) > 1 {
					attr, ok := traversal[1].(hcl.TraverseAttr)
					if ok && ((name == "local" && !locals[attr.Name]) || (name == "var" && !variables[attr.Name])) {
						return fmt.Errorf("unresolved monitoring reference %s.%s", name, attr.Name)
					}
				}
			}
		}
		for _, block := range body.Blocks {
			if err := checkBody(block.Body); err != nil {
				return err
			}
		}
		return nil
	}
	if err := checkBody(parsed.Body.(*hclsyntax.Body)); err != nil {
		return nil, err
	}
	// Standalone owner cannot silently fall back to blue resource-derived names.
	editable, diags := hclwrite.ParseConfig(config, "observability.tf", hcl.InitialPos)
	if diags.HasErrors() {
		return nil, diags
	}
	for _, block := range editable.Body().Blocks() {
		if block.Type() == "variable" && block.Labels()[0] == "datadog_observability_hosts" {
			block.Body().RemoveAttribute("default")
			block.Body().SetAttributeRaw("nullable", hclwrite.Tokens{{Type: hclsyntax.TokenIdent, Bytes: []byte("false")}})
		}
	}
	versions := []byte(`terraform {
 required_version = ">= 1.9, < 2.0"
 required_providers { datadog = { source = "DataDog/datadog", version = "= 4.25.0" } }
 backend "gcs" {}
}
# DD_API_KEY and DD_APP_KEY are supplied through the private operator environment.
provider "datadog" { api_url = "https://api.${var.datadog_site}/" }
`)
	handoff := make([]map[string]any, 0, len(observabilityAddresses))
	for _, address := range observabilityAddresses {
		handoff = append(handoff, map[string]any{"source_address": address + "[0]", "destination_address": address + "[0]", "existing_remote_id": nil})
	}
	manifest, _ := json.MarshalIndent(map[string]any{"schema": 1, "exclusive_state_ownership_required": true, "resources": handoff}, "", "  ")
	return map[string][]byte{"observability.tf": hclwrite.Format(editable.Bytes()), "versions.tf": hclwrite.Format(versions), "ownership-handoff.json": append(manifest, '\n')}, nil
}

func containsString(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}

func rewriteObservabilityBlock(source []byte, block *hclsyntax.Block, replacements map[string]string) ([]byte, error) {
	r := block.Range()
	text := string(source[r.Start.Byte:r.End.Byte])
	type edit struct {
		start, end int
		value      string
	}
	var edits []edit
	diags := hclsyntax.VisitAll(block.Body, func(node hclsyntax.Node) hcl.Diagnostics {
		expression, ok := node.(*hclsyntax.ScopeTraversalExpr)
		if !ok {
			return nil
		}
		span := expression.Range()
		if replacement, ok := replacements[string(source[span.Start.Byte:span.End.Byte])]; ok {
			edits = append(edits, edit{span.Start.Byte - r.Start.Byte, span.End.Byte - r.Start.Byte, replacement})
		}
		return nil
	})
	if diags.HasErrors() {
		return nil, diags
	}
	sort.Slice(edits, func(i, j int) bool { return edits[i].start > edits[j].start })
	for _, e := range edits {
		text = text[:e.start] + e.value + text[e.end:]
	}
	return []byte(text), nil
}

// The operator runs this only on a reviewed saved plan after separately approved
// exclusive state transfer. It rejects creation/import/replacement/destruction
// and requires the exact preexisting IDs from the reviewed ownership handoff.
func observabilityPlanCommand() *cobra.Command {
	var planPath, handoffPath string
	command := &cobra.Command{Use: "check-plan", Short: "Refuse a Datadog plan that changes ownership or touches any other resource", Args: cobra.NoArgs, SilenceUsage: true}
	command.Flags().StringVar(&planPath, "plan", "", "Saved Terraform plan JSON")
	command.Flags().StringVar(&handoffPath, "handoff", "", "Reviewed ownership handoff with exact existing remote IDs")
	_ = command.MarkFlagRequired("plan")
	_ = command.MarkFlagRequired("handoff")
	command.RunE = func(cmd *cobra.Command, _ []string) error {
		plan, err := os.ReadFile(planPath)
		if err != nil {
			return err
		}
		handoff, err := os.ReadFile(handoffPath)
		if err != nil {
			return err
		}
		if err = checkObservabilityPlan(plan, handoff); err != nil {
			return err
		}
		_, err = fmt.Fprintln(cmd.OutOrStdout(), "Plan retains exact reviewed Datadog ownership; no create/import/delete/replacement or non-Datadog changes.")
		return err
	}
	return command
}

func checkObservabilityPlan(planJSON, handoffJSON []byte) error {
	var handoff struct {
		Schema    int `json:"schema"`
		Resources []struct {
			Source      string  `json:"source_address"`
			Destination string  `json:"destination_address"`
			ID          *string `json:"existing_remote_id"`
		} `json:"resources"`
	}
	if err := json.Unmarshal(handoffJSON, &handoff); err != nil || handoff.Schema != 1 {
		return errors.New("invalid reviewed ownership handoff")
	}
	ids := map[string]string{}
	for _, entry := range handoff.Resources {
		if entry.Source != entry.Destination || !containsString(observabilityAddresses, strings.TrimSuffix(entry.Source, "[0]")) || !strings.HasSuffix(entry.Source, "[0]") {
			return errors.New("handoff address outside closed owner set")
		}
		if _, exists := ids[entry.Source]; exists {
			return errors.New("duplicate handoff owner")
		}
		ids[entry.Source] = ""
		if entry.ID != nil {
			ids[entry.Source] = *entry.ID
		}
	}
	if len(ids) != len(observabilityAddresses) {
		return errors.New("incomplete ownership handoff")
	}
	var plan struct {
		Errored  bool              `json:"errored"`
		Deferred []json.RawMessage `json:"deferred_changes"`
		Changes  []struct {
			Address string `json:"address"`
			Mode    string `json:"mode"`
			Change  struct {
				Actions   []string        `json:"actions"`
				Before    map[string]any  `json:"before"`
				After     map[string]any  `json:"after"`
				Importing json.RawMessage `json:"importing"`
			} `json:"change"`
		} `json:"resource_changes"`
	}
	if err := json.Unmarshal(planJSON, &plan); err != nil || plan.Errored || len(plan.Deferred) > 0 || len(plan.Changes) == 0 {
		return errors.New("invalid, deferred or empty owner plan")
	}
	seen := map[string]bool{}
	for _, resource := range plan.Changes {
		id, known := ids[resource.Address]
		if !known || id == "" || seen[resource.Address] || resource.Mode != "managed" {
			return errors.New("unreviewed resource or missing preexisting remote ID")
		}
		seen[resource.Address] = true
		change := resource.Change
		if len(change.Actions) != 1 || (change.Actions[0] != "no-op" && change.Actions[0] != "update") || (len(change.Importing) > 0 && string(change.Importing) != "null") {
			return errors.New("owner plan must not create, import, destroy or replace resources")
		}
		if change.Before["id"] != id || change.After["id"] != id {
			return errors.New("planned remote ID differs from the reviewed existing owner")
		}
	}
	for address, id := range ids {
		if id != "" && !seen[address] {
			return errors.New("reviewed existing resource omitted from plan")
		}
	}
	return nil
}
