// Package freeradius renders static native backend configuration. Installation,
// ownership, validation and activation are privileged adapter responsibilities.
package freeradius

import (
	"bytes"
	"embed"
	"errors"
	"net"
	"net/netip"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"text/template"
)

//go:embed *.tmpl
var templates embed.FS

type Client struct {
	ID, Location, Secret string
	CIDRs                []string
}
type Options struct {
	SourceConfigSHA256                                                        string
	Host, Generation, ConfigDir, AuthDirectory, SpoolDirectory, LeafDirectory string
	CertificateFile, KeyFile, CAFile, PolicyAddress, Bearer, NativeConninfo   string
	Clients                                                                   []Client
	Legacy                                                                    bool
	ListenIPv6                                                                bool
	// Include is the fixed root-only clients include produced by source apply.
	SourcesInclude bool
}

var identifier = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_.:-]{0,127}$`)
var path = regexp.MustCompile(`^/[a-zA-Z0-9_./-]+$`)

func quote(s string) string { return strconv.Quote(s) }
func Render(o Options) (map[string][]byte, error) {
	if (o.SourcesInclude || o.SourceConfigSHA256 != "") && !regexp.MustCompile(`^[a-f0-9]{64}$`).MatchString(o.SourceConfigSHA256) {
		return nil, errors.New("invalid native source configuration identity")
	}
	if !identifier.MatchString(o.Host) || !regexp.MustCompile(`^[a-f0-9]{16,64}$`).MatchString(o.Generation) {
		return nil, errors.New("invalid native host or generation")
	}
	for _, v := range []string{o.ConfigDir, o.AuthDirectory, o.SpoolDirectory, o.LeafDirectory, o.CertificateFile, o.KeyFile, o.CAFile} {
		if !path.MatchString(v) || filepath.Clean(v) != v {
			return nil, errors.New("invalid native path")
		}
	}
	if o.AuthDirectory == o.SpoolDirectory {
		return nil, errors.New("auth and accounting require separate directories")
	}
	h, p, e := net.SplitHostPort(o.PolicyAddress)
	ip, ie := netip.ParseAddr(h)
	port, pe := strconv.Atoi(p)
	if e != nil || ie != nil || !ip.IsLoopback() || pe != nil || port < 1 || port > 65535 {
		return nil, errors.New("native policy endpoint must be loopback")
	}
	if !regexp.MustCompile(`^[a-zA-Z0-9_-]{32,256}$`).MatchString(o.Bearer) {
		return nil, errors.New("invalid native bearer")
	}
	// NativeConninfo is generated by the native adapter after verified-TLS checks.
	// Still reject config/expansion injection at this serialization boundary.
	if len(o.NativeConninfo) > 8192 || strings.ContainsAny(o.NativeConninfo, "\r\n\x00%$`") || (!strings.Contains(o.NativeConninfo, "sslmode=verify-full") && !strings.Contains(o.NativeConninfo, "sslmode=verify-ca")) {
		return nil, errors.New("invalid native verified connection")
	}
	seen := map[string]bool{}
	o.ListenIPv6 = false
	for _, c := range o.Clients {
		if !identifier.MatchString(c.ID) || !identifier.MatchString(c.Location) || seen[c.ID] || len(c.Secret) < 8 || len(c.Secret) > 256 || strings.ContainsAny(c.Secret, "\r\n\x00%$`") {
			return nil, errors.New("invalid native client")
		}
		seen[c.ID] = true
		for _, cidr := range c.CIDRs {
			p, e := netip.ParsePrefix(cidr)
			if e != nil || p.Bits() == 0 || p != p.Masked() {
				return nil, errors.New("invalid native source range")
			}
			if p.Addr().Is6() {
				o.ListenIPv6 = true
			}
		}
	}
	result := map[string][]byte{}
	for name, destination := range map[string]string{"radiusd": "radiusd.conf", "dictionary": "dictionary", "clients": "clients.conf", "eap": "mods-enabled/eap", "rest": "mods-enabled/rest", "sql": "mods-enabled/sql", "accounting": "mods-enabled/accounting_detail", "auth": "mods-enabled/auth_detail", "always": "mods-enabled/always", "default": "sites-enabled/default", "certificate": "sites-enabled/certificate", "buffered": "sites-enabled/buffered"} {
		raw, e := templates.ReadFile(name + ".tmpl")
		if e != nil {
			return nil, e
		}
		t, e := template.New(name).Funcs(template.FuncMap{"quote": quote}).Parse(string(raw))
		if e != nil {
			return nil, e
		}
		var b bytes.Buffer
		if e = t.Execute(&b, o); e != nil {
			return nil, e
		}
		result[destination] = b.Bytes()
	}
	return result, nil
}
