package binding

import (
	"bytes"
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// Deterministic fixture is independently generated by the existing Python implementation.
const legacyToken = "c8021x.1.AAAAAGVT8QAHBwcHBwcHBwcHBwehoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoQB4ZmFrZTox7MkocAuxVawVAbc_UiY7LqpXCANpxMoHpjjJ6xEPXR4"

func TestLegacyWireParityAndOriginalReceiptTime(t *testing.T) {
	key := bytes.Repeat([]byte("A"), 64)
	v := 120
	token, err := IssueWithRandom(key, Attribution{DeviceID: "fake:1", Fingerprint: strings.Repeat("a1", 32), VLAN: &v}, "nyc", "AA-BB-CC-DD-EE-FF", time.Unix(1700000000, 0), bytes.NewReader(bytes.Repeat([]byte{7}, 12)))
	if err != nil {
		t.Fatal(err)
	}
	if token != legacyToken {
		t.Fatalf("wire parity %s", token)
	}
	for _, station := range []string{"aabb.ccdd.eeff", "AABBCCDDEEFF", "aa:bb:cc:dd:ee:ff"} {
		for _, value := range []string{token, "0x" + hex.EncodeToString([]byte(token))} {
			got := Verify(key, []string{value}, "nyc", []string{station}, time.Unix(1700000001, 0), MaxAge)
			if got == nil || got.DeviceID != "fake:1" || got.Fingerprint != strings.Repeat("a1", 32) || *got.VLAN != 120 {
				t.Fatalf("verify %+v", got)
			}
		}
	}
	// Processing after a month still uses the original authenticated receipt timestamp.
	if Verify(key, []string{token}, "nyc", []string{"AABBCCDDEEFF"}, time.Unix(1700000001, 0), MaxAge) == nil {
		t.Fatal("lost original receipt")
	}
}
func TestBindingsFailToUnattributed(t *testing.T) {
	key := bytes.Repeat([]byte("A"), 64)
	now := time.Unix(1700000000, 0)
	token, err := Issue(key, Attribution{DeviceID: "fake:1", Fingerprint: strings.Repeat("a1", 32)}, "nyc", "AABBCCDDEEFF", now)
	if err != nil {
		t.Fatal(err)
	}
	if got := Verify(key, []string{token}, "nyc", []string{"AABBCCDDEEFF"}, now, MaxAge); got == nil || got.VLAN != nil {
		t.Fatal("no VLAN sentinel")
	}
	for _, tc := range []struct {
		key      []byte
		tokens   []string
		site     string
		stations []string
		receipt  time.Time
	}{
		{key, nil, "nyc", []string{"AABBCCDDEEFF"}, now}, {key, []string{token, token}, "nyc", []string{"AABBCCDDEEFF"}, now}, {key, []string{token}, "nyc", []string{"AABBCCDDEEFF", "AABBCCDDEEFF"}, now}, {bytes.Repeat([]byte("B"), 64), []string{token}, "nyc", []string{"AABBCCDDEEFF"}, now}, {key, []string{token}, "other", []string{"AABBCCDDEEFF"}, now}, {key, []string{token}, "nyc", []string{"112233445566"}, now}, {key, []string{token}, "nyc", []string{"AABBCCDDEEFF"}, now.Add(-time.Second)}, {key, []string{token}, "nyc", []string{"AABBCCDDEEFF"}, now.Add(MaxAge)},
	} {
		if Verify(tc.key, tc.tokens, tc.site, tc.stations, tc.receipt, MaxAge) != nil {
			t.Fatalf("attributed invalid %+v", tc)
		}
	}
	for _, bad := range []string{"arbitrary", "0x00", token + "=", strings.Replace(token, ".1.", ".2.", 1), token[:len(token)-1] + "!", strings.Repeat("a", 509)} {
		if Verify(key, []string{bad}, "nyc", []string{"AABBCCDDEEFF"}, now, MaxAge) != nil {
			t.Fatalf("bad %s", bad)
		}
	}
	for _, id := range []string{"", strings.Repeat("x", 97)} {
		if _, err := Issue(key, Attribution{DeviceID: DeviceID(id), Fingerprint: strings.Repeat("a1", 32)}, "nyc", "AABBCCDDEEFF", now); err == nil {
			t.Fatal("bad id")
		}
	}
	token, err = Issue(key, Attribution{DeviceID: DeviceID(strings.Repeat("x", 96)), Fingerprint: strings.Repeat("a1", 32)}, "nyc", "AABBCCDDEEFF", now)
	if err != nil || len(token) > 253 {
		t.Fatal("wire bound")
	}
}
func TestBindingKeyWhitespaceCompatibility(t *testing.T) {
	path := filepath.Join(t.TempDir(), "key")
	key := bytes.Repeat([]byte("A"), 4096)
	if err := os.WriteFile(path, append(key, '\n'), 0600); err != nil {
		t.Fatal(err)
	}
	got, err := ReadKey(path)
	if err != nil || !bytes.Equal(got, key) {
		t.Fatal("legacy key newline", err)
	}
}
